# These are supported funding model platforms

github: KyLeggiero # Up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: BlueHuskyStudios
open_collective: # A single Open Collective username
ko_fi: BlueHuskyStudios
tidelift: # A single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # A single Community Bridge project-name e.g., cloud-foundry
liberapay: # A single Liberapay username
issuehunt: # A single IssueHunt username
otechie: # A single Otechie username
custom: ['https://PayPal.me/BenLeggiero'] # Up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
